config/routes.rb
Rails.application.routes.draw do

  get 'contact/contact'

  get 'contact/all_contact'

  resources :groups
# Series

 

# USERS / ADMIN
  get 'all_users'=> 'admin#all_users'

  get 'edit_user' => 'admin#edit_user'

  post 'edit_user' => 'admin#edit_user'

  get 'show_user'=>'admin#show_user'

  get 'delete_user'=> 'admin#delete_user'

  devise_scope :user do

  get 'login' => 'devise/sessions#create'

  post 'login' => 'devise/sessions#create'

  end

 # CART
  post 'add_to_cart'=> 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  get 'edit_item' => 'cart#edit_line_item'

  post 'order_complete' => 'cart#order_complete'

  get 'edit_line_item' => 'cart#edit_line_item'

  post 'edit_line_item' => 'cart#edit_line_item'

  post 'delete_line_item' => 'cart#delete_line_item'
  
  get 'delete_line_item' => 'cart#delete_line_item'

# MAIN NAVIGATIONS 
  root 'portfolio#index'

  get 'store'=> 'storefront#all_items'

  get 'categorical' => 'storefront#items_by_category'

  get 'about' => 'portfolio#about'

  # get 'login' => 'users#edit'

# Portfolio

  get 'index' => 'portfolio#index'

  get 'previous_work' => 'portfolio#previous_work'

  get 'portfolio'=> 'portfolio#portfolio'


# Series / Groups

  get 'groups_all' => 'groups#all_groups'

  get 'groups_fineart' => 'groups#fineart_groups'

   get 'groups_index' => 'groups#index'

  devise_for :users
  resources :products

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  include Transloadit::Rails::ParamsDecoder

  before_action :authenticate_user!, expcept: [:add_to_cart, :view_order]

  def add_to_cart
    #lets add a message that will not allow our user to add '0' quantity

    if params[:quantity].to_i == 0
      flash[:notice] = "Please enter a valid quantity to add to cart!"
      redirect_back(fallback_location: root_path) 

      #if user provides valid information we next check to see if the item has already been
      #added to prevent duplicates
    else

#call current_order      
    @order = current_order

       line_item = @order.line_items.where(product_id: params[:product_id].to_i).first
        #if line_item is not found, we create it.
        if line_item.blank?
          line_item = @order.line_items.new(product_id: params[:product_id], quantity: params[:quantity])

          @order.save
          session[:order_id] = @order.id

          line_item.update(line_item_total: (line_item.quantity * line_item.product.price))

        else
        #if found, we update it with the additional quantity
          new_quantity = line_item.quantity + params[:quantity].to_i
          line_item.update(quantity: new_quantity)
          line_item.update(line_item_total: (line_item.quantity * line_item.product.price))    

        end 
      redirect_back(fallback_location: root_path)
    end
  end

  def checkout

    line_items = current_order.line_items

    if line_items.length != 0 

      current_order.update(user_id: current_user.id, subtotal: 0)

      @order = current_order

        line_items.each do |item|
          item.product.update(quantity: (item.product.quantity - item.quantity))
          @order.order_items[item.product_id] = item.quantity
          @order.subtotal += item.line_item_total
        end
      @order.save

      @order.update(sales_tax: (@order.subtotal * 0.08))
      @order.update(grand_total: (@order.sales_tax + @order.subtotal))

      @order.line_items.destroy_all

      session[:order_id] = nil
    end
  end


  def delete_line_item
    line_item = current_order.line_items.find_by(product_id: params[:product_id].to_i)
    line_item.destroy

    redirect_back(fallback_location: view_order)
       
  end

  def edit_line_item

    line_item = current_order.line_items.find_by(product_id: params[:product_id].to_i)
    line_item.update(quantity: params[:quantity].to_i)
    line_item.update(line_item_total: line_item.quantity * line_item.product.price)

    redirect_back(fallback_location: view_order)
  end

  def order_complete
    @order = Order.find(params[:order_id])
    @amount = (@order.grand_total.to_f.round(2) * 100).to_i

    @order.line_items.destroy_all
    session[:order_id] = nil


    customer = Stripe::Customer.create(
      :email => current_user.email,
      :card => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :description => 'Cynzia\'s Customer',
      :currency => 'usd'
    )

    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to cart_path

  end

  def view_order
    @line_items = current_order.line_items

    @cart_total = 0

    @line_items.each do |item|
      @cart_total += item.line_item_total
    end
    
  end

end

app/helpers/cart_helper.rb
module CartHelper
end

app/views/cart/add_to_cart.html.erb
<h1>Cart#add_to_cart</h1>
<p>Find me in app/views/cart/add_to_cart.html.erb</p>

app/views/cart/checkout.html.erb
<h2>Thanks for Shopping with us <%= current_user.email %>!</h2>
<p>Let's review your order:</p>

<% @order.order_items.each do |k,v| %>
	<ul>
		<li>Item Name: <%= Product.find(k).name %>, <%= v %></li>
	</ul>
<% end %>


<p>
  <strong>Subtotal: </strong><%= number_to_currency @order.subtotal %> 
</p>

<p>
  <strong>Sales Tax: </strong><%= number_to_currency @order.sales_tax %> 
</p>
<p>
	<strong>Order Total:</strong> <%= number_to_currency @order.grand_total %>
</p>



<div>
  <%= form_tag order_complete_path do %>
    <article>
      <label class="amount">
        <span><%= number_to_currency @order.grand_total %></span>
      </label>
    </article>
    <div>
      <%= hidden_field_tag :order_id, @order.id %>
    </div>

    <script src="http://checkout.stripe.com/checkout.js"
    class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="Order #<%= @order.id %>"
    data-amount="<%= (@order.grand_total.to_f.round(2) * 100) %>"></script>
  <% end %>
</div>

app/views/cart/order_complete.html.erb
<h2>Thank you for your order!</h2>

<p>
  Order #<%= @order.id %> will be shipping to you, 
  <%= @order.user.email %>, as soon as possible!
</p>

<%= link_to 'Back to Shopping', store_path, class: "btn btn-warning" %>

app/views/cart/view_order.html.erb
<h1>My Cart</h1>


	<% if @line_items != nil %>
			<p> Your Items Are: </p>

<!-- new stuff -->

<table class='table'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Piece</th>
      <th>Price</th>
      <th>Quantity</th>
      <th>subtotal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @line_items.each do |item| %>
      <tr>
      	<td><%= item.product.name %></td>
        <td><%= image_tag item.product.image.url, class: "thumb" %></td>
        <td><%= number_to_currency item.product.price %></td>
        <td><%= item.quantity %></td>
        <td><%= number_to_currency item.line_item_total %></td>
     

   		 <td><%= form_tag edit_line_item_path do %>
          <%= hidden_field_tag :order_id, item.order_id %>
          <%= hidden_field_tag :product_id, item.product_id %>
          <%= number_field_tag :quantity, nil, min: 0, max: item.product.quantity, class: "form-control" %>
          <%= submit_tag "Edit Quantity", class: "btn btn-primary" %>
         <% end %> 
       </td>
        <td><%= link_to "Delete", delete_line_item_path(product_id: item.product_id, order_id: item.order_id), class: "btn btn-danger" %></td>

      </tr>
    <% end %>
  </tbody>
</table>

<br>

	<% else %>
	 		<p> There are no items </p>
	<% end %>
<!-- end new stuff -->

	<%= link_to "Proceed to Checkout", checkout_path, class: "btn btn-warning right-side"%>