config/routes.rb
Rails.application.routes.draw do

  get 'contact/contact'

  get 'contact/all_contact'

  resources :groups
# Series

 

# USERS / ADMIN
  get 'all_users'=> 'admin#all_users'

  get 'edit_user' => 'admin#edit_user'

  post 'edit_user' => 'admin#edit_user'

  get 'show_user'=>'admin#show_user'

  get 'delete_user'=> 'admin#delete_user'

  devise_scope :user do

  get 'login' => 'devise/sessions#create'

  post 'login' => 'devise/sessions#create'

  end

 # CART
  post 'add_to_cart'=> 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  get 'edit_item' => 'cart#edit_line_item'

  post 'order_complete' => 'cart#order_complete'

  get 'edit_line_item' => 'cart#edit_line_item'

  post 'edit_line_item' => 'cart#edit_line_item'

  post 'delete_line_item' => 'cart#delete_line_item'
  
  get 'delete_line_item' => 'cart#delete_line_item'

# MAIN NAVIGATIONS 
  root 'portfolio#index'

  get 'store'=> 'storefront#all_items'

  get 'categorical' => 'storefront#items_by_category'

  get 'about' => 'portfolio#about'

  # get 'login' => 'users#edit'

# Portfolio

  get 'index' => 'portfolio#index'

  get 'previous_work' => 'portfolio#previous_work'

  get 'portfolio'=> 'portfolio#portfolio'


# Series / Groups

  get 'groups_all' => 'groups#all_groups'

  get 'groups_fineart' => 'groups#fineart_groups'

   get 'groups_index' => 'groups#index'

  devise_for :users
  resources :products

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)

            if user.admin?
                can :manage, Product
            elsif user.guest?
                can :show, Product
            end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user 
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. 
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord


	

end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/group.rb
class Group < ApplicationRecord
	mount_uploader :image, ImageUploader
	
	has_many :products

end

app/models/line_item.rb
class LineItem < ApplicationRecord

	belongs_to :product
	belongs_to :order, optional: true


end

app/models/order.rb
class Order < ApplicationRecord

	has_many :line_items
	belongs_to :user, optional: true

	serialize :order_items, Hash
end

app/models/picture.rb
class Picture < ApplicationRecord


end

app/models/product.rb
class Product < ApplicationRecord
	mount_uploader :image, ImageUploader
	
	belongs_to :group, optional: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :orders

  def admin?
  	role == "admin"
  end

  def guest?
  	role == "guest"
  end	


end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  include Transloadit::Rails::ParamsDecoder
  before_action :authenticate_user!

  def all_users
  	
  	if current_user.role != 'admin'
  		
  		redirect_to root_path, :notice => 'Admin credentials needed for Admin links.'
  		
  	end	
		@users = User.all
  end

  
  def edit_user
  	@user = User.find(params[:id])
  	@user.update(role: params[:role])
  	redirect_back(fallback_location: root_path)


  end

  def show_user
  	@user = User.find(params[:id])
  end


  def delete_user
    @user = User.find(params[:id].to_i)
    @user.destroy
    redirect_to all_users_pathr
  end
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  include Transloadit::Rails::ParamsDecoder

  before_action :authenticate_user!, expcept: [:add_to_cart, :view_order]

  def add_to_cart
    #lets add a message that will not allow our user to add '0' quantity

    if params[:quantity].to_i == 0
      flash[:notice] = "Please enter a valid quantity to add to cart!"
      redirect_back(fallback_location: root_path) 

      #if user provides valid information we next check to see if the item has already been
      #added to prevent duplicates
    else

#call current_order      
    @order = current_order

       line_item = @order.line_items.where(product_id: params[:product_id].to_i).first
        #if line_item is not found, we create it.
        if line_item.blank?
          line_item = @order.line_items.new(product_id: params[:product_id], quantity: params[:quantity])

          @order.save
          session[:order_id] = @order.id

          line_item.update(line_item_total: (line_item.quantity * line_item.product.price))

        else
        #if found, we update it with the additional quantity
          new_quantity = line_item.quantity + params[:quantity].to_i
          line_item.update(quantity: new_quantity)
          line_item.update(line_item_total: (line_item.quantity * line_item.product.price))    

        end 
      redirect_back(fallback_location: root_path)
    end
  end

  def checkout

    line_items = current_order.line_items

    if line_items.length != 0 

      current_order.update(user_id: current_user.id, subtotal: 0)

      @order = current_order

        line_items.each do |item|
          item.product.update(quantity: (item.product.quantity - item.quantity))
          @order.order_items[item.product_id] = item.quantity
          @order.subtotal += item.line_item_total
        end
      @order.save

      @order.update(sales_tax: (@order.subtotal * 0.08))
      @order.update(grand_total: (@order.sales_tax + @order.subtotal))

      @order.line_items.destroy_all

      session[:order_id] = nil
    end
  end


  def delete_line_item
    line_item = current_order.line_items.find_by(product_id: params[:product_id].to_i)
    line_item.destroy

    redirect_back(fallback_location: view_order)
       
  end

  def edit_line_item

    line_item = current_order.line_items.find_by(product_id: params[:product_id].to_i)
    line_item.update(quantity: params[:quantity].to_i)
    line_item.update(line_item_total: line_item.quantity * line_item.product.price)

    redirect_back(fallback_location: view_order)
  end

  def order_complete
    @order = Order.find(params[:order_id])
    @amount = (@order.grand_total.to_f.round(2) * 100).to_i

    @order.line_items.destroy_all
    session[:order_id] = nil


    customer = Stripe::Customer.create(
      :email => current_user.email,
      :card => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer => customer.id,
      :amount => @amount,
      :description => 'Cynzia\'s Customer',
      :currency => 'usd'
    )

    rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to cart_path

  end

  def view_order
    @line_items = current_order.line_items

    @cart_total = 0

    @line_items.each do |item|
      @cart_total += item.line_item_total
    end
    
  end

end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/storefront_helper.rb
module StorefrontHelper
end

app/views/admin/all_users.html.erb
<h1>All Our Users</h1>

<div class="continer center-it">
	<% @users.each do |user| %>
		<div class="row">
			<h3><strong>User:</strong> 	<%= link_to user.email, show_user_path(id: user.id) %> </h3>
			<p><strong>Role: </strong><%= user.role %></p>

		</div>
	<% end %>
</div>

app/views/admin/delete_user.html.erb
<h1>Admin#delete_user</h1>
<p>Find me in app/views/admin/delete_user.html.erb</p>

app/views/admin/edit_user.html.erb
<h1>Admin#edit_user</h1>
<p>Find me in app/views/admin/edit_user.html.erb</p>

app/views/admin/show_user.html.erb
<h1> User Profile for <%= @user.email %></h1>

<p><strong>User: </strong><%= @user.email %></p>
<p><strong>Role: </strong><%= @user.role %></p>

<% if can? :manage, User %>

	<div class="well">

		<%= form_tag edit_user_path do %>

		<%= select_tag(:role, options_for_select(["admin", "employee", "guest"]), :prompt => "Please select") %>
			<%= hidden_field_tag :id, @user.id %>
			<%= submit_tag "Update Role", class: "btn btn-warning" %>

		<% end %>

		<%= link_to "Delete User", delete_user_parth(id: @user.id), class: 'btn btn-danger' %>
	</div>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cynzia</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class='container'>

    <!-- Start of nav bar -->
    <nav class="navbar navbar-default">

      <div class="container-fluid">

        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">

          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
  <!-- TITLE  -->

        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav navbar-left nav-title"> <li><%= link_to "Home", root_path %></li></ul>
          

          <ul class="nav navbar-nav">

  <!-- Main Navs-->
    <!-- Fine Art -->
       <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Fine Art </a>
          <ul class="dropdown-menu">
         
              
          <li><%= link_to "All", portfolio_path(category: "Fine Art") %></li>

          <li><%= link_to "Series", groups_all_path %></li>    
              
         
          </ul>
        </li>
   
         

          
  <!-- Portraits -->
       <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Portraits </a>
          <ul class="dropdown-menu">
         
              
          <li><%= link_to "People", portfolio_path(category: "People Portraits") %></li>

          <li><%= link_to "Pets", portfolio_path(category: "Pet Portraits") %></li>                
              
         
          </ul>
        </li>
  
  <!--  Other Options-->
       <li class="dropdown ">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"> <span class="caret"></span></a>
            <ul class="dropdown-menu">
      <!-- About / store -->
                <li><%= link_to "About", about_path %></li>
                <li><%= link_to "Store", store_path %></li>
                <li><%= link_to "Previous Work", previous_work_path(previous_work: :previous_work) %></li>  
                <hr>
      <!-- Conact Modal -->            
                <li>
                  <a href="#" class="" data-toggle="modal" data-toggle="modal" data-target="#myModal">
                    Contact
                  </a>
                </li>
      <!-- Login / user session -->
          <% if user_signed_in? %>
       
                <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
                <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
               </li>
            
            <% else %>
                 <li> <%= link_to "Login", login_path %></li>
            <% end %>
          </li>
            
         </ul> 
       </li>

    <!-- ADMIN -->
        <% if user_signed_in? %>

          <% if can? :manage, Product %>
                    
           <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><p class="glyphicon glyphicon-heart red"></p></a>
              <ul class="dropdown-menu">

                
                <li><%= link_to "Users", all_users_path %></li>
              
                <li><%= link_to "Pieces", products_path %></li>

                <li><%= link_to "Series", groups_index_path %></li>
              </ul>
            </li>
          <% end %>
        <% end %>

      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>
<!-- End of Nav bar -->
<!--  Cart Icon -->



  <div class="container">
        <div class="cart">
      
     
        <% if current_order.line_items.length != 0 %>
            <li><%= link_to  view_order_path do %>
              <%= image_tag "full_cart.png", class: 'cart-pic pull-right'%></li>
          <% end %>
        <% end %>
        </div>
  </div>
<!--  End of Cart Icon -->
   		 <%= yield %>

<!-- FOOTER -->

<!-- END FOOTER -->
      <!-- Modal -->
      <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
       
            </div>
            <!-- MODAL BODY  -->
            <div class="modal-body">
          
            </div>

      <!-- MODAL FOOTER -->

            <div class="modal-footer">
             <p>
              
                
              
             </p>

            </div>
     <!-- END MODAL FOOTER -->
          </div>
        </div>
      </div>
  </div>
  </body>
</html>