config/routes.rb
Rails.application.routes.draw do

  get 'contact/contact'

  get 'contact/all_contact'

  resources :groups
# Series

 

# USERS / ADMIN
  get 'all_users'=> 'admin#all_users'

  get 'edit_user' => 'admin#edit_user'

  post 'edit_user' => 'admin#edit_user'

  get 'show_user'=>'admin#show_user'

  get 'delete_user'=> 'admin#delete_user'

  devise_scope :user do

  get 'login' => 'devise/sessions#create'

  post 'login' => 'devise/sessions#create'

  end

 # CART
  post 'add_to_cart'=> 'cart#add_to_cart'

  get 'view_order' => 'cart#view_order'

  get 'checkout' => 'cart#checkout'

  get 'edit_item' => 'cart#edit_line_item'

  post 'order_complete' => 'cart#order_complete'

  get 'edit_line_item' => 'cart#edit_line_item'

  post 'edit_line_item' => 'cart#edit_line_item'

  post 'delete_line_item' => 'cart#delete_line_item'
  
  get 'delete_line_item' => 'cart#delete_line_item'

# MAIN NAVIGATIONS 
  root 'portfolio#index'

  get 'store'=> 'storefront#all_items'

  get 'categorical' => 'storefront#items_by_category'

  get 'about' => 'portfolio#about'

  # get 'login' => 'users#edit'

# Portfolio

  get 'index' => 'portfolio#index'

  get 'previous_work' => 'portfolio#previous_work'

  get 'portfolio'=> 'portfolio#portfolio'


# Series / Groups

  get 'groups_all' => 'groups#all_groups'

  get 'groups_fineart' => 'groups#fineart_groups'

   get 'groups_index' => 'groups#index'

  devise_for :users
  resources :products

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/group.rb
class Group < ApplicationRecord
	mount_uploader :image, ImageUploader
	
	has_many :products

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  include Transloadit::Rails::ParamsDecoder

  before_action :set_group, only: [:show, :edit, :update, :destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = Group.all
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  def all_groups
    @groups = Group.all
    @products = Product.all
  end
  

  def fineart_groups
    @products = Product.where(series_name: params[:name])
    @product = @products.first

    @carousel = []
     
     @products.each do |product|

        @carousel.push(product.image)
   
    end
    
  end



  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :year, :description, :total_qty, :image)
    end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group, local: true) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this series from being saved:</h2>

      <ul>
      <% group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<!-- Upload an Image -->
   <div class="field">



    <%= form.label :image, class: "products-label" %>
    <%= form.file_field :image, id: :image, class: "products-pic" %>
  </div>

  <div class="field">
    <%= form.label :name, class: "products-label"  %>
    <%= form.text_field :name, id: :series_name, class: "btn btn-default form-control" %>
  </div>
<!-- year  -->
  <div class="field">
    <%= form.label :year, class: "products-label"  %>
    <%= form.number_field :year, id: :series_year, in: 1960...2070, class: "btn btn-default form-control" %>
  </div>

  <div class="field">
    <%= form.label :description, class: "products-label"  %>
    <%= form.text_field :description, id: :series_description, class: "btn btn-default form-control" %>
  </div>

 <br />

  <div class="actions">
    <%= form.button "Create Series", class: "btn btn-warning" %>


  <%= link_to 'All Series', groups_index_path, class: "btn btn-default"  %>
   </div>
<% end %>

app/views/groups/all_groups.html.erb
<h1 class="storefront-title"> All Series</h1>

<div class ="masonary-row row">
	<% @groups.each do |s| %>
		<div class="col-xs-12 col-sm-6 col-lg-6">
			<div class="panel center-it">
				
			<%= link_to groups_fineart_path(name: s.name) do %>
				<%= image_tag s.image , class: "storefront-pic" %>
			<% end %>

				<h3 class="storefront-text"><%= s.name %></h3>
				<p class="storefront-text"><%= s.description %></p> 
				<%= link_to "See More", groups_fineart_path(name: s.name), class: "btn btn-default storefront-text" %>
				<p></p>

			</div>
		</div>
	<% end %>
</div>

app/views/groups/edit.html.erb
<h1>Editing Group</h1>

<%= render 'form', group: @group %>

<%= link_to 'Show', @group %> |
<%= link_to 'Back', groups_path %>

app/views/groups/fineart_groups.html.erb
<h3 class="portfolio-title">Series: <%= @product.series_name  %></h3>

	<div id="slideshow" class="sliders center-it" style:"clear:both;">
		<%= @products %>

	      <% @carousel.each do |carousel| %>

	      <%= image_tag carousel, class: "slide"%>

	      <% end %>
	</div>

<br />

<div class ="masonary-row row">
	<% @products.each do |product| %>

		<div class="col-xs-12 col-sm-6 col-lg-6">
				<div class="panel center-it">

					<% if product.image.url.nil? == false %>
						<%= image_tag product.image, class: "storefront-pic" %>
					<% end %>

					<p>
					<h3  class="storefront-text"><%= product.name %></h3>
					<a href="#" class="btn btn-default storefront-text" data-toggle="modal" data-toggle="modal" data-target="#myModal_<%= product.id %>">
						<span class="glyphicon glyphican-plus"></span>Details
					</a>
				</p>
				</div>


		</div>

<!-- Modal -->
			<div class="modal fade" id="myModal_<%= product.id %>" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
			  <div class="modal-dialog" role="document">
			    <div class="modal-content">
			      <div class="modal-header">
			        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
			 
			      </div>
			      <!-- MODAL BODY  -->
			      <div class="modal-body">
			      	<% if product.image.url.nil? == false%>
			      		<p><%= image_tag product.image.url, class: "storefront-pic" %></p>	      		
			      	<% end %>

			      		<h3 class="storefront-title-modal"><%= product.name %></h3>
			      		<% if product.series_name != nil  %>
									<p class="storefront-text"><span class="red">Series: </span><%=  product.series_name %></p>			
								<% end %>      		

			      		<p class="storefront-text"><span class="red">Year: </span><%=  product.year %></p>
			      		<p class="storefront-text"><span class="red">Medium: </span><%= product.medium %></p>
			      		<p class="storefront-text"><span class="red">Size: </span><%= product.size %></p>
			      		<p class="storefront-text"><span class="red">Details: </span><%= product.description %></p>

			      		<% if user_signed_in? %>
			      		<% if can? :manage, product %>
			      			 <td><%= link_to 'Edit', edit_product_path(product), class: "btn btn-default btn-modal" %></td>
			      		<% end %>
			      		<% end %>


	
			      </div>

      <!-- MODAL FOOTER -->

			      <div class="modal-footer">
			       <p>
			       	<%= form_tag add_to_cart_path do %>
			       		<%= hidden_field_tag :product_id, product.id %>
			       		
			       	<% end %>
			       </p>

		      		<p>
			       		<%if product.quantity != 0 && product.for_sale == true%>
				      
				       	<%= form_tag add_to_cart_path do %>
				       		<%= hidden_field_tag :product_id, product.id %>
				       		<%= number_field_tag :quantity, nil, min: 0, max: product.quantity,  placeholder: "Qty?", class: "store-qty-form"%>
				       		<%= submit_tag "Add to Cart", class: "btn btn-warning" %>
				       	<% end %>
				      <% end %>
				     </p>
			      </div>
	   <!-- END MODAL FOOTER -->
			    </div>
			  </div>
			</div>
	<!-- END OF MODAL -->
	<% end %>
</div>

app/views/groups/index.html.erb
<p id="notice"><%= notice %></p>


<h1 class="storefront-title">All Series</h1>

<%= link_to 'New Series', new_group_path, class: "btn btn-default" %>

  <table class="table">
    <thead>
      <tr class="red">
        <th>Image</th>
        <th>Name</th>
        <th>Year</th>
        <th>Description</th>
        <th>Total qty</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody> 
      <% @groups.each do |series| %>
        <tr>
         
          <td><%= image_tag series.image.url, class: "thumb" %></td>
          <td><%= series.name %></td>
          <td><%= series.year %></td>
          <td><%= series.description %></td>
          <td><%= series.total_qty %></td>
          <td><%= link_to 'Show', series, class: "btn btn-default" %></td>
          <td><%= link_to 'Edit', edit_group_path(series), class: "btn btn-default" %></td>
          <td><%= link_to 'Destroy', series, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-default" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

<br>

<%= link_to 'New Series', new_group_path, class: "btn btn-default" %>

app/views/groups/new.html.erb
<h1>New Series</h1>

<%= render 'form', group: @group %>

app/views/groups/show.html.erb
<p id="notice"><%= notice %></p>



 <div class="col col-lg-2 col-mid-4 col-sm-4">
    <p>
      <strong class="red">Series Name:</strong>
      <%= @group.name %>
    </p>

    <p>
      <strong class="red">Year:</strong>
      <%= @group.year %>
    </p>

    <p>
      <strong class="red">Description:</strong>
      <%= @group.description %>
    </p>

    <p>
      <strong class="red">Total qty:</strong>
      <%= @group.total_qty %>
    </p>

    <%= link_to 'Edit', edit_group_path(@group), class: "btn btn-default" %> 
    <%= link_to 'All Series', groups_index_path, class: "btn btn-default" %>
    <%= link_to 'New Series', new_group_path, class: "btn btn-default" %>



  </div>
  <div class="col col-lg-10 col-md-8 col-sm-8">
 <p>
  <%= image_tag @group.image, class: "admin-show-pic"%>
</p>
</div>